name: "Common airport Checkin"

on:
  schedule:
    - cron: "0 22 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run sign
        env:
          AMOUNT: ${{ secrets.AMOUNT }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          for i in $(seq 1 AMOUNT): do
            URL: ${{ secrets.${{ URL${{ i }} }} }}
            EMAIL: ${{ secrets.${{ EMAIL${{ i }} }} }}
            PASSWD: ${{ secrets.${{ PASSWD${{ i }} }} }}
            python3 ./main.py
          done
          
